---
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JMoney417/spring-config-server
          searchPaths: petclinic
server:
  port: 8888
